### ISSUE TITLE
Typo: `PRIM_GLTF_ALPHA_MODE_OPAQUE` >> `PRIM_GLTF_ALPHA_MODE_NONE`

### ISSUE THREAD

**Issue by buildersbrewery** [Sei-Lisa/kwdb#13]
Typo: `PRIM_GLTF_ALPHA_MODE_OPAQUE` >> `PRIM_GLTF_ALPHA_MODE_NONE`

SL wiki says none. FYI, didn't double-check viewer (... yet).

**Comment by buildersbrewery** [comment]
Ok, I now saw Sei-Lisa/kwdb@746ef67.

**Comment by Sei-Lisa** [comment]
That's the reason why [this](https://github.com/Sei-Lisa/kwdb/blob/master/outputs/constants-test-sl.lsl), [this](https://github.com/Sei-Lisa/kwdb/blob/master/outputs/functioncheck-sl.lsl) and [this](https://github.com/Sei-Lisa/kwdb/blob/master/outputs/last-func-const-check-sl.txt) exist. Linden Lab are prone to mistakes <del>documenting stuff</del> in general.
