### ISSUE TITLE
Time to update the kwdb?

### ISSUE THREAD

**Issue by clairem-sl** [Sei-Lisa/kwdb#3]
[According to Inara Pey](https://modemworld.me/2023/01/31/2023-sl-sug-meetings-week-5-summary/), the following 5 functions are now in General Availability for all mainstream regions:

* [llAdjustSoundVolume()](https://wiki.secondlife.com/wiki/LlAdjustSoundVolume).
* [llLinkSetSoundRadius()](https://wiki.secondlife.com/wiki/LlSetSoundRadius).
* [llLinkStopSound()](https://wiki.secondlife.com/wiki/LlLinkStopSound).
* [llLinkSetSoundQueueing()](https://wiki.secondlife.com/wiki/LlLinkSetSoundQueueing).
* [llLinkPlaySound()](https://wiki.secondlife.com/wiki/LlLinkPlaySound).

**Comment by Sei-Lisa** [comment]
Thanks for the heads-up. I've been lagging behind in tracking LL changes; apologies. These functions and associated constants have been added now.
